default: &default
  SECRET_KEY: your_secret_key_here
  JWT_SECRET_KEY: your_jwt_secret_key_here
  SQLALCHEMY_TRACK_MODIFICATIONS: false
  JWT_ACCESS_TOKEN_EXPIRES: 3600  # 1 hour
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0
  MAIL_SERVER: smtp.gmail.com
  MAIL_PORT: 587
  MAIL_USE_TLS: true
  MAIL_USERNAME: your_email@gmail.com
  MAIL_PASSWORD: your_email_password
  MAIL_DEFAULT_SENDER: your_email@gmail.com
  PLAID_CLIENT_ID: your_plaid_client_id
  PLAID_SECRET: your_plaid_secret
  PLAID_ENV: development
  UPLOAD_FOLDER: /app/uploads
  MAX_CONTENT_LENGTH: 16 * 1024 * 1024  # 16 MB

development:
  <<: *default
  DEBUG: true
  SQLALCHEMY_DATABASE_URI: postgresql://user:password@db/dev_db
  PLAID_ENV: sandbox

testing:
  <<: *default
  TESTING: true
  SQLALCHEMY_DATABASE_URI: postgresql://user:password@db/test_db
  PLAID_ENV: sandbox

production:
  <<: *default
  DEBUG: false
  SQLALCHEMY_DATABASE_URI: postgresql://user:password@db/prod_db
  PLAID_ENV: production