default: &default
  SECRET_KEY: your_secret_key_here
  JWT_SECRET_KEY: your_jwt_secret_key_here
  JWT_ACCESS_TOKEN_EXPIRES: 3600  # 1 hour
  CELERY_BROKER_URL: redis://localhost:6379/0
  CELERY_RESULT_BACKEND: redis://localhost:6379/0
  MAIL_SERVER: smtp.gmail.com
  MAIL_PORT: 587
  MAIL_USE_TLS: true
  MAIL_USERNAME: your_email@gmail.com
  MAIL_PASSWORD: your_email_password
  MAIL_DEFAULT_SENDER: your_email@gmail.com
  PLAID_CLIENT_ID: your_plaid_client_id
  PLAID_SECRET: your_plaid_secret
  PLAID_ENV: development
  UPLOAD_FOLDER: /app/uploads
  MAX_CONTENT_LENGTH: 16777216  # 16 MB

database: &database
  DB_HOST: "100.64.88.44"
  DB_PORT: "5432"
  DB_USER: larrimore
  DB_PASSWORD: larrimore
  DB_NAME: finance

development:
  <<: *default
  <<: *database
  DEBUG: true
  SQLALCHEMY_DATABASE_URI: postgresql://%(DB_USER)s:%(DB_PASSWORD)s@%(DB_HOST)s:%(DB_PORT)s/%(DB_NAME)s
  PLAID_ENV: sandbox

testing:
  <<: *default
  <<: *database
  TESTING: true
  DB_NAME: test_db
  SQLALCHEMY_DATABASE_URI: postgresql://%(DB_USER)s:%(DB_PASSWORD)s@%(DB_HOST)s:%(DB_PORT)s/%(DB_NAME)s
  PLAID_ENV: sandbox

production:
  <<: *default
  <<: *database
  DEBUG: false
  DB_NAME: prod_db
  SQLALCHEMY_DATABASE_URI: postgresql://%(DB_USER)s:%(DB_PASSWORD)s@%(DB_HOST)s:%(DB_PORT)s/%(DB_NAME)s
  PLAID_ENV: production