"""empty message

Revision ID: 335ecfe4b362
Revises: 3f0cd927c06e
Create Date: 2024-07-11 14:06:02.451836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335ecfe4b362'
down_revision = '3f0cd927c06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_paid_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('last_paid_date')

    # ### end Alembic commands ###
