"""empty message

Revision ID: 3f0cd927c06e
Revises: e0e4bc2be47b
Create Date: 2024-07-11 11:34:30.745991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f0cd927c06e'
down_revision = 'e0e4bc2be47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billPDF')
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('is_credit_card', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_credit_card')
        batch_op.drop_column('account_id')

    op.create_table('billPDF',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name='billPDF_bill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='billPDF_pkey')
    )
    # ### end Alembic commands ###
