"""bills model

Revision ID: d82a72556656
Revises: 56eb3c251e29
Create Date: 2024-07-10 20:12:14.507037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd82a72556656'
down_revision = '56eb3c251e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_pdf')
    op.add_column('bill', sa.Column('payment_status', sa.String(length=20), nullable=True))
    op.add_column('bill', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill', 'category')
    op.drop_column('bill', 'payment_status')
    op.create_table('bill_pdf',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('bill_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name='bill_pdf_bill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bill_pdf_pkey')
    )
    # ### end Alembic commands ###
