"""Add relationship between Bill and Transaction

Revision ID: e0e4bc2be47b
Revises: d82a72556656
Create Date: 2024-07-10 20:21:24.629754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0e4bc2be47b'
down_revision = 'd82a72556656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('bill_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'transaction', 'bill', ['bill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'bill_id')
    # ### end Alembic commands ###
